### ISSUE TITLE
Play/Pause button crashes when library is empty

### ISSUE THREAD

**Issue by JPaulMora** [timonmw/Musify#1]
Stack trace:

````
FATAL EXCEPTION: main
                                                                     Process: com.timon.gugb.musify, PID: 1954
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'int com.timon.gugb.musify.utils.SongList.size()' on a null object reference
                                                                         at com.timon.gugb.musify.services.MediaPlayerService.playNext(MediaPlayerService.java:252)
                                                                         at com.timon.gugb.musify.services.MediaPlayerService.onCompletion(MediaPlayerService.java:278)
                                                                         at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2584)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
````

Error is in MediaPlayerService.java when PlayNext() calls currSongList.size();

**Comment by JPaulMora** [comment]
I think the error is caused by Player class not passing a SongList to MediaPlayerService otherwise SongList isn't being initialized properly.
